import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import postsRouter from "./routes/post.route.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/posts", postsRouter);
connectDB();
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
